#!/usr/bin/env bash
#transfers a file from our client to a server

let "args = 3"

if [ $# -lt "$args" ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

file_path = $1
dest_ip = $2
username = $3
ssh_priv_key = $4

scp -i $ssh_priv_key $file_path $username@to_host:$dest_ip
