#!/usr/bin/env bash
#Configures a new Ubuntu machine to run Nginx

#install Nginx
sudo apt-get -y update && sudo apt-get -y install nginx

#firewall configuration
sudo ufw enable
sudo ufw allow 'Nginx HTTP'

#When querying Nginx at its root / with a GET
#request (requesting a page) using curl, it must
#return a page that contains the string Hello World!
echo -e "Hello World!\n" > /var/www/html/index.html
