#!/usr/bin/env bash
#enable a dedicated PPA with the following command:
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5

#install haproxy 2.5
sudo apt-get -y install haproxy=2.5.\*

#configure haproxy
sudo echo -e "backend web-backend\n\tmode tcp\n\tbalance roundrobin\n\tserver 1138-web-01 3.236.17.147:80 check\n\tserver 1138-web-02 34.204.172.13:80 check\n\n" >> /etc/haproxy/haproxy.cfg

sudo echo -e "frontend haproxy\n\tmode tcp\n\tbind *:80\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg

#allow to manage HAProxy via an init script,
#the following change has to be done:
sudo echo "ENABLED=1" >> /etc/default/haproxy

#restart haproxy
sudo service haproxy restart
sudo /etc/init.d/haproxy restart
